//go:build engine_assets

// Code generated by scripts/prepare-engine.sh. DO NOT EDIT.

package engine

import "embed"

//go:embed all:engine_venv
var venvFS embed.FS

//go:embed all:engine_ffmpeg
var ffmpegFS embed.FS
