//go:build engine_assets

// Code generated by scripts/prepare-engine.sh. DO NOT EDIT.

package engine

import (
	"embed"
	"errors"
	"io/fs"
)

// ErrNoEmbeddedAssets is referenced by the stub build too; keep it in sync
// with embed_stub.go.
var ErrNoEmbeddedAssets = errors.New("engine: gömülü motor varlıkları bulunamadı (build sırasında 'make build' veya -tags engine_assets kullanın)")

// probeEmbedded verifies the embedded FSes are usable at runtime.
func probeEmbedded() error {
	if _, err := fs.ReadFile(venvFS, "engine_venv/.engine-stamp"); err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return errors.New("engine: gömülü venv bozuk (engine-stamp eksik)")
		}
		return err
	}
	return nil
}

//go:embed all:engine_venv
var venvFS embed.FS

//go:embed all:engine_ffmpeg
var ffmpegFS embed.FS
