#!/usr/bin/env bash
# prepare-engine.sh — build the embedded Python download engine for musicle-cli.
#
# Creates a Python venv at assets/engine/venv with spotdl + yt-dlp installed,
# downloads a static ffmpeg into assets/engine/ffmpeg/<os>-<arch>/, and
# writes a sentinel so `go build` can embed everything via go:embed.
#
# Usage:
#   ./scripts/prepare-engine.sh [linux|windows|darwin]
#
# The chosen OS is the host where `ffmpeg` will run. Cross-compile support
# for the Python venv is platform-agnostic (pure Python pip installs).

set -euo pipefail

OS_TARGET="${1:-linux}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ASSETS="$ROOT/assets/engine"
VENV="$ASSETS/venv"
FFMPEG_DIR="$ASSETS/ffmpeg/$OS_TARGET-amd64"

mkdir -p "$ASSETS" "$FFMPEG_DIR"

echo "==> Target OS: $OS_TARGET"
echo "==> Python venv: $VENV"
echo "==> ffmpeg dir:  $FFMPEG_DIR"

# ---------- Python venv ----------
# Resolve the interpreter path according to the target OS layout so we never
# fall back to a Windows-style Scripts/python.exe on Linux (or vice versa).
venv_python() {
    case "$OS_TARGET" in
        windows) echo "$VENV/Scripts/python.exe" ;;
        *)       echo "$VENV/bin/python" ;;
    esac
}

if [ ! -d "$VENV" ]; then
    echo "==> Creating Python virtualenv..."
    python3 -m venv "$VENV"
else
    echo "==> Existing venv found at $VENV"
fi

PYBIN="$(venv_python)"
if [ ! -x "$PYBIN" ]; then
    echo "==> venv python kullanılamaz ($PYBIN), venv yeniden oluşturuluyor..."
    rm -rf "$VENV"
    python3 -m venv "$VENV"
    PYBIN="$(venv_python)"
fi

if [ ! -x "$PYBIN" ]; then
    echo "ERROR: venv python hâlâ bulunamadı: $PYBIN" >&2
    echo "python3 kurulu mu? (gerekirse: sudo dnf install python3)" >&2
    exit 1
fi

echo "==> Upgrading pip..."
"$PYBIN" -m pip install --upgrade pip wheel setuptools >/dev/null

echo "==> Installing yt-dlp and spotdl..."
"$PYBIN" -m pip install \
    "yt-dlp==2024.12.13" \
    "spotdl==4.4.0" >/dev/null

# Stamp version so the Go side can verify cache freshness.
echo "engine-version=1" > "$VENV/.engine-stamp"

# ---------- ffmpeg ----------
if [ -x "$FFMPEG_DIR/ffmpeg" ] || [ -x "$FFMPEG_DIR/ffmpeg.exe" ]; then
    echo "==> Reusing existing ffmpeg in $FFMPEG_DIR"
else
    echo "==> Downloading static ffmpeg for $OS_TARGET..."
    case "$OS_TARGET" in
        linux)
            URL="https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz"
            TMP="$(mktemp -d)"
            curl -sL "$URL" -o "$TMP/ffmpeg.tar.xz"
            tar -xJf "$TMP/ffmpeg.tar.xz" -C "$TMP"
            # Find ffmpeg and ffprobe binaries and copy only those.
            BIN="$(find "$TMP" -type f -name ffmpeg | head -1)"
            PROBE="$(find "$TMP" -type f -name ffprobe | head -1)"
            [ -n "$BIN" ] && cp "$BIN" "$FFMPEG_DIR/ffmpeg" && chmod +x "$FFMPEG_DIR/ffmpeg"
            [ -n "$PROBE" ] && cp "$PROBE" "$FFMPEG_DIR/ffprobe" && chmod +x "$FFMPEG_DIR/ffprobe"
            rm -rf "$TMP"
            ;;
        windows)
            URL="https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip"
            TMP="$(mktemp -d)"
            curl -sL "$URL" -o "$TMP/ffmpeg.zip"
            unzip -q "$TMP/ffmpeg.zip" -d "$TMP"
            BIN="$(find "$TMP" -type f -iname 'ffmpeg.exe' | head -1)"
            PROBE="$(find "$TMP" -type f -iname 'ffprobe.exe' | head -1)"
            [ -n "$BIN" ] && cp "$BIN" "$FFMPEG_DIR/ffmpeg.exe"
            [ -n "$PROBE" ] && cp "$PROBE" "$FFMPEG_DIR/ffprobe.exe"
            rm -rf "$TMP"
            ;;
        darwin)
            URL="https://evermeet.cx/ffmpeg/getrelease/zip"
            TMP="$(mktemp -d)"
            curl -sL "$URL" -o "$TMP/ffmpeg.zip"
            unzip -q "$TMP/ffmpeg.zip" -d "$FFMPEG_DIR"
            curl -sL "https://evermeet.cx/ffmpeg/getrelease/ffprobe/zip" -o "$TMP/ffprobe.zip"
            unzip -q "$TMP/ffprobe.zip" -d "$FFMPEG_DIR"
            rm -rf "$TMP"
            chmod +x "$FFMPEG_DIR/ffmpeg" "$FFMPEG_DIR/ffprobe"
            ;;
        *)
            echo "Unknown OS: $OS_TARGET" >&2
            exit 1
            ;;
    esac
fi

echo "==> Generating embed_assets.go for the Go side..."
GEN="$ROOT/internal/engine/embed_assets.go"
cat > "$GEN" <<EOF
//go:build engine_assets

// Code generated by scripts/prepare-engine.sh. DO NOT EDIT.

package engine

import (
	"embed"
	"errors"
	"io/fs"
)

// ErrNoEmbeddedAssets is referenced by the stub build too; keep it in sync
// with embed_stub.go.
var ErrNoEmbeddedAssets = errors.New("engine: gömülü motor paketi derlenmedi (build tag engine_assets gerekli)")

// probeEmbedded verifies the embedded FSes are usable at runtime.
func probeEmbedded() error {
	if _, err := fs.ReadFile(venvFS, ".engine-stamp"); err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return errors.New("engine: gömülü venv bozuk (engine-stamp eksik)")
		}
		return err
	}
	return nil
}

//go:embed all:engine_venv
var venvFS embed.FS

//go:embed all:engine_ffmpeg
var ffmpegFS embed.FS
EOF

# Move the prepared dirs into a location go:embed can reach.
mkdir -p "$ROOT/internal/engine/engine_venv" "$ROOT/internal/engine/engine_ffmpeg"
# Use rsync if available, else cp -r.
if command -v rsync >/dev/null 2>&1; then
    rsync -a --delete "$VENV"/ "$ROOT/internal/engine/engine_venv/"
    rsync -a --delete "$FFMPEG_DIR"/ "$ROOT/internal/engine/engine_ffmpeg/"
else
    rm -rf "$ROOT/internal/engine/engine_venv" "$ROOT/internal/engine/engine_ffmpeg"
    cp -r "$VENV" "$ROOT/internal/engine/engine_venv"
    cp -r "$FFMPEG_DIR" "$ROOT/internal/engine/engine_ffmpeg"
fi

echo "==> Done. Embedded engine ready at internal/engine/{engine_venv,engine_ffmpeg}."
